'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Wpf16_Enlace_Controles_

    Partial Public Class NorthwindEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=NorthwindEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Employees() As DbSet(Of Employees)
        Public Overridable Property Order_Details() As DbSet(Of Order_Details)
        Public Overridable Property Orders() As DbSet(Of Orders)
    
    End Class

End Namespace
