'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultasMantenimiento

    Partial Public Class Software
        Public Property CodSoftware As String
        Public Property Nombre As String
        Public Property MemoriaRequerida As Nullable(Of Short)
        Public Property ProcesadorRequerido As Nullable(Of Short)
        Public Property DiscoRequerido As Nullable(Of Short)
        Public Property Version As String
        Public Property Distribuidor As String
        Public Property Precio As Nullable(Of Decimal)
        Public Property Categoria As Boolean
    
        Public Overridable Property Instalaciones As ICollection(Of Instalaciones) = New HashSet(Of Instalaciones)
    
    End Class

End Namespace
