'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultasMantenimiento

    Partial Public Class Usuarios
        Public Property CodUsuario As String
        Public Property Nombre As String
        Public Property Apellido As String
        Public Property Telefono As String
        Public Property Direccion As String
        Public Property CodEquipo As String
    
        Public Overridable Property Equipos As Equipos
    
    End Class

End Namespace
