'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WindowsApp1

    Partial Public Class Categorias
        Public Property IdCategoria As Integer
        Public Property Titulo As String
        Public Property Descripcion As String
    
        Public Overridable Property Anuncios As ICollection(Of Anuncios) = New HashSet(Of Anuncios)
    
    End Class

End Namespace
