'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Linq2

    Partial Public Class DaniDBEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=DaniDBEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Pilotos() As DbSet(Of Pilotos)
        Public Overridable Property Reservas() As DbSet(Of Reservas)
        Public Overridable Property Viajeros() As DbSet(Of Viajeros)
        Public Overridable Property Viajes() As DbSet(Of Viajes)
    
    End Class

End Namespace
