'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Linq2

    Partial Public Class Pilotos
        Public Property CodPiloto As Integer
        Public Property Nombre As String
        Public Property HorasVuelo As Nullable(Of Integer)
        Public Property DNI As String
        Public Property Direccion As String
        Public Property Telefono As String
    
        Public Overridable Property Viajes As ICollection(Of Viajes) = New HashSet(Of Viajes)
    
    End Class

End Namespace
