'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Linq2

    Partial Public Class Reservas
        Public Property CodReserva As Integer
        Public Property CodViaje As Nullable(Of Integer)
        Public Property CodViajero As Nullable(Of Integer)
        Public Property Precio As Nullable(Of Double)
    
        Public Overridable Property Viajeros As Viajeros
        Public Overridable Property Viajes As Viajes
    
    End Class

End Namespace
