'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Linq2

    Partial Public Class Viajeros
        Public Property CodViajero As Integer
        Public Property Nombre As String
        Public Property Direccion As String
        Public Property DNI As String
        Public Property Telefono As String
        Public Property Ciudad As String
    
        Public Overridable Property Reservas As ICollection(Of Reservas) = New HashSet(Of Reservas)
    
    End Class

End Namespace
