'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Linq2

    Partial Public Class Viajes
        Public Property CodViaje As Integer
        Public Property Destino As String
        Public Property PlazasMax As Nullable(Of Integer)
        Public Property PlazasMin As Nullable(Of Integer)
        Public Property FechaSalida As Nullable(Of Date)
        Public Property FechaRegreso As Nullable(Of Date)
        Public Property CodPiloto As Nullable(Of Integer)
    
        Public Overridable Property Pilotos As Pilotos
        Public Overridable Property Reservas As ICollection(Of Reservas) = New HashSet(Of Reservas)
    
    End Class

End Namespace
