'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ComboBox

    Partial Public Class Mensajes
        Public Property idmensaje As Integer
        Public Property Idusuario As String
        Public Property Fecha As Nullable(Of Date)
        Public Property Mensaje As String
        Public Property id As Nullable(Of Integer)
    
        Public Overridable Property Usuarios As Usuarios
    
    End Class

End Namespace
