'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ComboBox

    Partial Public Class Usuarios
        Public Property idusuario As String
        Public Property palabrapaso As String
        Public Property Nombre As String
        Public Property Apellidos As String
        Public Property dni As String
        Public Property email As String
        Public Property Edad As Nullable(Of Integer)
    
        Public Overridable Property Mensajes As ICollection(Of Mensajes) = New HashSet(Of Mensajes)
    
    End Class

End Namespace
