'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lineas
    Public Property FacturaId As Integer
    Public Property ArticuloId As Integer
    Public Property Unidades As Nullable(Of Integer)

    Public Overridable Property Articulos As Articulos
    Public Overridable Property Facturas As Facturas

End Class
