'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultasMantenimiento

    Partial Public Class Equipos
        Public Property cod_equipo As String
        Public Property Procesador As String
        Public Property Velocidad As Nullable(Of Short)
        Public Property CD_ROM As Nullable(Of Byte)
        Public Property Memoria As Short
        Public Property tarjeta_red As String
        Public Property disco_duro As Single
        Public Property Uso As Boolean
    
        Public Overridable Property Instalaciones As ICollection(Of Instalaciones) = New HashSet(Of Instalaciones)
        Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
    
    End Class

End Namespace
