'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultasMantenimiento

    Partial Public Class Instalaciones
        Public Property cod_instalacion As String
        Public Property cod_equipo As String
        Public Property cod_software As String
        Public Property fecha_instalacion As Nullable(Of Date)
    
        Public Overridable Property Equipos As Equipos
        Public Overridable Property Software As Software
    
    End Class

End Namespace
