'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WPFAnuncios

    Partial Public Class Anuncios
        Public Property IdAnuncio As Integer
        Public Property IdAnunciante As Nullable(Of Integer)
        Public Property Slogan As String
        Public Property Foto As Byte()
    
        Public Overridable Property Anunciantes As Anunciantes
    
    End Class

End Namespace
