'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WPFAnuncios

    Partial Public Class Categorias
        Public Property IdCategoria As Integer
        Public Property Nombre As String
    
        Public Overridable Property Anunciantes As ICollection(Of Anunciantes) = New HashSet(Of Anunciantes)
    
    End Class

End Namespace
