'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace WPFAnuncios

    Partial Public Class DaniDBEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=DaniDBEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Anunciantes() As DbSet(Of Anunciantes)
        Public Overridable Property Anuncios() As DbSet(Of Anuncios)
        Public Overridable Property Categorias() As DbSet(Of Categorias)
    
    End Class

End Namespace
