'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WPF15_menus_

    Partial Public Class Menus
        Public Property IdMenu As Integer
        Public Property Titulo As String
        Public Property Parent As Nullable(Of Integer)
    
        Public Overridable Property Menus1 As ICollection(Of Menus) = New HashSet(Of Menus)
        Public Overridable Property Menus2 As Menus
    
    End Class

End Namespace
