'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultasLinq

    Partial Public Class Products
        Public Property ProductID As Integer
        Public Property ProductName As String
        Public Property SupplierID As Nullable(Of Integer)
        Public Property CategoryID As Nullable(Of Integer)
        Public Property QuantityPerUnit As String
        Public Property UnitPrice As Nullable(Of Decimal)
        Public Property UnitsInStock As Nullable(Of Short)
        Public Property UnitsOnOrder As Nullable(Of Short)
        Public Property ReorderLevel As Nullable(Of Short)
        Public Property Discontinued As Boolean
    
        Public Overridable Property Order_Details As ICollection(Of Order_Details) = New HashSet(Of Order_Details)
    
    End Class

End Namespace
