'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Examen_UrkoUrbieta28012020

    Partial Public Class Emisiones
        Public Property cod_emision As Integer
        Public Property cod_cine As String
        Public Property cod_pelicula As String
        Public Property hora As Nullable(Of Date)
    
        Public Overridable Property Cines As Cines
        Public Overridable Property Peliculas As Peliculas
    
    End Class

End Namespace
