'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Examen_UrkoUrbieta28012020

    Partial Public Class Peliculas
        Public Property cod_pelicula As String
        Public Property titulo As String
        Public Property duracion As Nullable(Of Integer)
    
        Public Overridable Property Emisiones As ICollection(Of Emisiones) = New HashSet(Of Emisiones)
    
    End Class

End Namespace
