'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultarVehiculos

    Partial Public Class CLIENTES
        Public Property DNI As String
        Public Property Nombre As String
        Public Property Domicilio As String
        Public Property Poblacion As String
        Public Property Codigo_postal As Nullable(Of Integer)
        Public Property Telefono As String
        Public Property Forma_de_pago As String
        Public Property SEXO As String
    
        Public Overridable Property NOTAS_REPARACIONES As ICollection(Of NOTAS_REPARACIONES) = New HashSet(Of NOTAS_REPARACIONES)
        Public Overridable Property VEHICULOS As ICollection(Of VEHICULOS) = New HashSet(Of VEHICULOS)
    
    End Class

End Namespace
