'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultarVehiculos

    Partial Public Class DETALLES_NOTAS
        Public Property Codigo_de_nota As Integer
        Public Property Linea As Integer
        Public Property Tipo As String
        Public Property Ampliacion As String
        Public Property Importe As Nullable(Of Decimal)
    
        Public Overridable Property NOTAS_REPARACIONES As NOTAS_REPARACIONES
    
    End Class

End Namespace
