'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ConsultarVehiculos

    Partial Public Class VEHICULOS
        Public Property matricula As String
        Public Property Marca As String
        Public Property Modelo As String
        Public Property Color As String
        Public Property Precio As Nullable(Of Decimal)
        Public Property anio As Nullable(Of Integer)
        Public Property DNI As String
        Public Property FECHA As Nullable(Of Date)
    
        Public Overridable Property CLIENTES As CLIENTES
    
    End Class

End Namespace
