'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WpfMateriales

    Partial Public Class Estados
        Public Property IdEstado As Integer
        Public Property Descripcion As String
    
        Public Overridable Property Materiales As ICollection(Of Materiales) = New HashSet(Of Materiales)
    
    End Class

End Namespace
