'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WpfMateriales

    Partial Public Class Materiales
        Public Property IdMaterial As Integer
        Public Property Marca As String
        Public Property Descripcion As String
        Public Property Estado As Nullable(Of Integer)
    
        Public Overridable Property Estados As Estados
        Public Overridable Property Movimientos As ICollection(Of Movimientos) = New HashSet(Of Movimientos)
    
    End Class

End Namespace
