'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WpfMateriales

    Partial Public Class Movimientos
        Public Property IdMovimiento As Integer
        Public Property IdMaterial As Nullable(Of Integer)
        Public Property Accion As Nullable(Of Byte)
        Public Property fecha As Nullable(Of Date)
    
        Public Overridable Property Acciones As Acciones
        Public Overridable Property Materiales As Materiales
    
    End Class

End Namespace
