'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Imagenes
    Public Property IdFoto As Integer
    Public Property Foto As Byte()
    Public Property Texto As String
    Public Property IdInmueble As String

    Public Overridable Property Inmuebles As Inmuebles

End Class
