'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inmuebles
    Public Property Id As String
    Public Property Descripcion As String
    Public Property Superficie As Nullable(Of Double)
    Public Property IdUsuario As String
    Public Property Tipo As Nullable(Of Integer)

    Public Overridable Property Imagenes As ICollection(Of Imagenes) = New HashSet(Of Imagenes)
    Public Overridable Property Tipos As Tipos
    Public Overridable Property Usuarios As Usuarios

End Class
