'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property Usuario As String
    Public Property Password As String
    Public Property Nombre As String
    Public Property Apellido As String

    Public Overridable Property Inmuebles As ICollection(Of Inmuebles) = New HashSet(Of Inmuebles)

End Class
