//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string GeneroID { get; set; }
        public string DeptID { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
