//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DAM_urkourbieta_DEVEntities1 : DbContext
    {
        public DAM_urkourbieta_DEVEntities1()
            : base("name=DAM_urkourbieta_DEVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
    
        public virtual ObjectResult<Empleados> getEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleados>("getEmpleados");
        }
    }
}
