//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebFrameworkConEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitarras
    {
        public int id_guitarra { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string forma { get; set; }
        public string pastillas { get; set; }
        public string color { get; set; }
        public decimal precio { get; set; }
    }
}
