'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace UrkoUrbietaExamenInterfaces19_02_2020

    Partial Public Class Productos
        Public Property id_producto As Integer
        Public Property descripcion As String
        Public Property precio As Nullable(Of Double)
        Public Property unidades As Nullable(Of Integer)
        Public Property imagen As Byte()
    
        Public Overridable Property Ventas As ICollection(Of Ventas) = New HashSet(Of Ventas)
    
    End Class

End Namespace
