'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace UrkoUrbietaExamenInterfaces19_02_2020

    Partial Public Class Ventas
        Public Property id_movimiento As Integer
        Public Property id_producto As Nullable(Of Integer)
        Public Property importe As Nullable(Of Double)
    
        Public Overridable Property Productos As Productos
    
    End Class

End Namespace
