'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LinQPrueba1

    Partial Public Class Categories
        Public Property CategoryID As Integer
        Public Property CategoryName As String
        Public Property Description As String
        Public Property Picture As Byte()
    
        Public Overridable Property Products As ICollection(Of Products) = New HashSet(Of Products)
    
    End Class

End Namespace
