'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LinQPrueba1

    Partial Public Class Employees
        Public Property EmployeeID As Integer
        Public Property LastName As String
        Public Property FirstName As String
        Public Property Title As String
        Public Property TitleOfCourtesy As String
        Public Property BirthDate As Nullable(Of Date)
        Public Property HireDate As Nullable(Of Date)
        Public Property Address As String
        Public Property City As String
        Public Property Region As String
        Public Property PostalCode As String
        Public Property Country As String
        Public Property HomePhone As String
        Public Property Extension As String
        Public Property Photo As Byte()
        Public Property Notes As String
        Public Property ReportsTo As Nullable(Of Integer)
        Public Property PhotoPath As String
    
        Public Overridable Property Employees1 As ICollection(Of Employees) = New HashSet(Of Employees)
        Public Overridable Property Employees2 As Employees
    
    End Class

End Namespace
