'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace LinQPrueba1

    Partial Public Class NorthwindEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=NorthwindEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Categories() As DbSet(Of Categories)
        Public Overridable Property Employees() As DbSet(Of Employees)
        Public Overridable Property Products() As DbSet(Of Products)
        Public Overridable Property Suppliers() As DbSet(Of Suppliers)
        Public Overridable Property Order_Details() As DbSet(Of Order_Details)
    
    End Class

End Namespace
