'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace LinQPrueba1

    Partial Public Class Order_Details
        Public Property OrderID As Integer
        Public Property ProductID As Integer
        Public Property UnitPrice As Decimal
        Public Property Quantity As Short
        Public Property Discount As Single
    
        Public Overridable Property Products As Products
    
    End Class

End Namespace
